// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:sipaksi/Module/Abstraction/MyReflectable.dart' as prefix0;
import 'package:sipaksi/Module/PenelitianInternal/List/Post.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.MyReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Post',
            r'.Post',
            134217735,
            0,
            const prefix0.MyReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({albumId, id, title, url, thumbnailUrl}) => b
                  ? prefix1.Post(
                      albumId: albumId,
                      id: id,
                      thumbnailUrl: thumbnailUrl,
                      title: title,
                      url: url)
                  : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 0,
              r'toString': 1,
              r'noSuchMethod': 0,
              r'hashCode': 1,
              r'runtimeType': 1,
              r'fromJson': 0,
              r'toJson': 1,
              r'albumId': 1,
              r'albumId=': 0,
              r'id': 1,
              r'id=': 0,
              r'title': 1,
              r'title=': 0,
              r'url': 1,
              r'url=': 0,
              r'thumbnailUrl': 1,
              r'thumbnailUrl=': 0
            })
      ],
      null,
      null,
      <Type>[prefix1.Post],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'fromJson': (dynamic instance) => instance.fromJson,
        r'toJson': (dynamic instance) => instance.toJson,
        r'albumId': (dynamic instance) => instance.albumId,
        r'id': (dynamic instance) => instance.id,
        r'title': (dynamic instance) => instance.title,
        r'url': (dynamic instance) => instance.url,
        r'thumbnailUrl': (dynamic instance) => instance.thumbnailUrl
      },
      {
        r'albumId=': (dynamic instance, value) => instance.albumId = value,
        r'id=': (dynamic instance, value) => instance.id = value,
        r'title=': (dynamic instance, value) => instance.title = value,
        r'url=': (dynamic instance, value) => instance.url = value,
        r'thumbnailUrl=': (dynamic instance, value) =>
            instance.thumbnailUrl = value
      },
      null,
      [
        const [1, 0, null],
        const [0, 0, null],
        const [
          0,
          0,
          const [#albumId, #id, #title, #url, #thumbnailUrl]
        ]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
